version: "3.8"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-pasajes
    working_dir: /var/www
    ports:
      - 8000:80
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - mysql
    networks:
      - networkapp

  mysql:
    image: mysql:5.7
    container_name: mysql-pasajes
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_HOST: mysql
    ports:
      - 33050:3306
    volumes:
      - .:/var/www
      - ./dbdatalaravel:/var/lib/mysql
      - ./etc/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - networkapp

  app:
    build:
      args:
        user: fdipaolo
        uid: 1001
      context: .
      dockerfile: ./Dockerfile
    container_name: app-pasajes
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - networkapp

networks:
  networkapp:

volumes:
  dbdatalaravel:
